### ISSUE TITLE
SyntaxError: Unexpected token '.' on new blog

### ISSUE THREAD

**Issue by MichalBryxi** [empress/empress-blog#101]
As title says. This is a brand new empress blog and it can't boot up:

```sh
❯ npm init ember-app acluxace
...
❯ cd acluxace
...
❯ npx ember-cli install empress-blog empress-blog-casper-template
...
❯ yarn start
```

The error in the console and on http://localhost:4200/

```sh
App is being served by FastBoot
/var/folders/8q/yrjx_8s115q43r8w5qd90_m00000gn/T/broccoli-29867Uz1ZZwXFtZq6/out-442-broccoli_merge_trees/assets/vendor.js:99690
      const description = this.currentRouteMeta?.description;
                                                ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at VMSandbox.eval (/Users/michal/pudr.com/acluxace/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /Users/michal/pudr.com/acluxace/node_modules/fastboot/src/ember-app.js:190:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/Users/michal/pudr.com/acluxace/node_modules/fastboot/src/ember-app.js:187:21)
    at EmberApp.retrieveSandboxedApp (/Users/michal/pudr.com/acluxace/node_modules/fastboot/src/ember-app.js:235:10)
    at new EmberApp (/Users/michal/pudr.com/acluxace/node_modules/fastboot/src/ember-app.js:61:21)
    at FastBoot._buildEmberApp (/Users/michal/pudr.com/acluxace/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/michal/pudr.com/acluxace/node_modules/fastboot/src/index.js:52:10)
    at /Users/michal/pudr.com/acluxace/node_modules/ember-cli-fastboot/index.js:335:29
```

And what is the app made of:

```sh
❯ grep 'ember-cli' package.json
    "ember-cli": "~3.23.0",
    "ember-cli-app-version": "^4.0.0",
    "ember-cli-babel": "^7.23.0",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-fastboot": "^2.2.3",
    "ember-cli-htmlbars": "^5.3.1",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-terser": "^4.0.1",
...
❯ grep 'empress' package.json
    "empress-blog": "^3.0.1",
    "empress-blog-casper-template": "^3.3.0",
```

**Comment by MichalBryxi** [comment]
So I found a hack to fix this by [enabling support for IE 11 in the builds](https://discord.com/channels/480462759797063690/480523424121356298/755455087308046337) (who would've guess that IE 11 would save me?). From the discussion it seems like it might [be a problem in ember-cli-terser](https://github.com/ember-cli/ember-cli-terser/issues/242)?

**Comment by MichalBryxi** [comment]
Ok, I think I found the source: 

- Current `ember-auto-import@^1.8.0` resolves to `1.10.1` (latest)
- This needs `webpack@^4.43.0`, which resolves to `4.44.2` (latest)
- Which needs `terser-webpack-plugin@^1.4.3`, which resolves to `1.4.5` (which is ancient, current is v5.0.3)
- And this one needs `terser@^4.1.2`, which resolves to `4.8.0`, but optional chaining was added to `terser` in `v5.2.0`

There is an [open PR against ember-auto-import](https://github.com/ef4/ember-auto-import/pull/327) to bump to webpack@v5.x, which has needed updates. I will try tomorrow to pin the version of `ember-auto-import` to see whether that helps.

**Comment by nickschot** [comment]
Which node version are you running? As I assume you're talking about dev mode (`yarn start`). This should work on node 14+. We'll need to fix this in empress-blog one way or another (either by dropping node < 14 or fixing transpilation).

**Comment by bendemboski** [comment]
Right, sorry for sowing some confusion here. This resembles the issue that is resolved with making sure `terser` is up-to-date, and maybe could be addressed with the same solution, but I think isn't really the same issue.

The issue I was referring to in the Discord convo was that terser was blowing up during the `ember-cli` build because its parser didn't understand the optional chaining operator, so it couldn't minify code that included it. Adding IE11 as a target "fixed" it because that would force babel to transpile the optional chaining operator to an older syntax that older versions of terser _would_ understand. But that's not a very good solution because it forces a whole bunch of other transpiling that isn't necessary. So updating terser to understand optional chaining is the best solution.

But here the error is happening in fastboot when loading a script and it looks like Node is throwing the error because the node version doesn't understand optional chaining. Adding IE11 would fix it for a similar reason, but would also have the same nasty side-effect of doing a whole bunch of other unnecessary transpiling. The equivalent of the better solution of updating terser here would be updating the NodeJS version that fastboot is running on to a version that understands optional chaining. IF that's not feasible, I think another solution would be to add whatever version of Node fastboot is running on to `config/targets.js`. I'm pretty sure the tooling that supports it understands Node versions, and then it would do only the transpiling needed for the code to be able to run on whatever the browser targets are and the Node version, rather than transpiling all the way back to IE11.

**Comment by MichalBryxi** [comment]
Aha! This helped 👍 

```sh
❯ node --version
v12.20.1 # fails with the error above

❯ node --version
v14.15.4 # works
```

I don't need to hold my project back on older node version. So this issue can be closed I guess. Thanks for your help!
