### ISSUE TITLE
Can't embed local images in markdown

### ISSUE THREAD

**Issue by elwayman02** [empress/empress-blog#109]
Even though the [guides](https://github.com/empress/empress-blog/blob/master/tests/dummy/content/the-editor.md) say you can drop images in the public folder and then reference them using `![alt text](/path/to/img.jpg)`, that doesn't actually work. The examples in your own dummy app only link to externally-hosted images rather than demonstrating how to use an image from the `public/` directory. When I tried to reference the path the same way we reference them in the frontmatter section (e.g. `/images/foo.jpg`), the image is not found. I also tried to reference it as a responsive image, since that's where the frontmatter images end up being processed to (e.g. `/responsive-images/foo2000w.jpg`). Neither approach worked, so can you explain how to embed images from `public/` in our markdown and/or update the guides accordingly?

**Comment by mansona** [comment]
so there is a few things going on here that could be causing your issue. Firstly you need to make sure that you have the config in your ember-cli-build that turns off fingerprinting for your images https://github.com/empress/empress-blog-netlify-casper-template/blob/master/ember-cli-build.js#L8 . There are many reasons for this but it's not really in the scope of this issue, but it should be added to your repo if you followed the quickstart (because of blueprints) so just double check that you're not doing something different 👍 if you want to make sure it's added you can run `ember g empress-blog` again to run the default blueprint again 

If you're having issues with responsive images then that's not because of empress-blog, we do not include `ember-responsive-images` in the empress-blog dependencies because of issues exactly like this. The only "official" empress-blog thing that has `ember-responsive-images` installed is https://github.com/empress/empress-blog-casper-template so either you should open this issue over there or you're dealing with a forked template and we can continue to discuss the issues with `ember-responsive-images` here 😂

**Comment by elwayman02** [comment]
Yes, I have fingerprinting off. I wasn't specifically trying to use responsive images, I just tried that path because I noted how the header images were being consumed. I was just trying to do a standard markdown reference to an image in `/public/images`, but it could not be found. So there is something else going on here.

**Comment by elwayman02** [comment]
To give an example of what I mean, here is where you actually talk about embedding images: https://github.com/empress/empress-blog/blame/master/tests/dummy/content/the-editor.md#L37

Note that even though you talk about pulling images from the local repo, you don't actually do that. Instead, it does this: `![Computer](https://casper.ghost.org/v1.0.0/images/computer.jpg)`, pulling the image from ghost's site instead via fully formed url.

**Comment by elwayman02** [comment]
Hmm, I don't know why it wasn't working before, but when I tried to reproduce it today, it worked. I'm going to submit a PR to update the demo app for empress-blog so that it's a real example and we can ensure it continues to work.
