### ISSUE TITLE
Page Scrolls to top when navigating

### ISSUE THREAD

**Issue by MalayaliRobz** [empress/empress-blog#29]
While clicking any link, the page scrolls to the top waits for like one second and then navigates to the corresponding link.
Video: 
![Apr-13-2019 14-17-29](https://user-images.githubusercontent.com/21201812/56077203-f24d4900-5df6-11e9-9464-89c37eead5ab.gif)

Would love if this could be made smoother, as of now something feels off.. when navigating.

**Comment by mansona** [comment]
@MalayaliRobz this has been mostly fixed by https://github.com/empress/empress-blog/pull/28 👍 the PR isn't quite ready to be merged yet but it will make this exact problem go away when navigating between the index and the post pages.

The same issue will still be there for cases where you are navigating between pages in pagination (you can [see an example here](https://empress-blog--ember-blog-legacy.netlify.com/) if you click the `older articles` link at the bottom). I don't really know the best way to make this feel "smoother" 🤔 I guess it will be a factor of the template, i.e. the casper template (when we enable pagination) will have an infinite scroll on the main page instead of having multiple pages (because that is just the way casper is implemented)

**Comment by mansona** [comment]
@MalayaliRobz this has been fixed in v1.6.0 🎉 

let me know if you still have any issues 👍
