### ISSUE TITLE
Running the app errors with `outputPath` of undefined in fastboot

### ISSUE THREAD

**Issue by knownasilya** [empress/empress-blog#6]
Cloned, `npm install`, `npm start`, visited localhost:4200

Node 8.9.1 and npm 6.1.0

```
TypeError: Cannot read property 'outputPath' of undefined
    at app.use (/Users/iradchenko/sandbox/ember-ghost/node_modules/ember-cli-fastboot/index.js:310:42)
    at Layer.handle [as handle_request] (/Users/iradchenko/sandbox/ember-ghost/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/iradchenko/sandbox/ember-ghost/node_modules/express/lib/router/index.js:317:13)
    at /Users/iradchenko/sandbox/ember-ghost/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/iradchenko/sandbox/ember-ghost/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/iradchenko/sandbox/ember-ghost/node_modules/express/lib/router/index.js:275:10)
    at compression (/Users/iradchenko/sandbox/ember-ghost/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/Users/iradchenko/sandbox/ember-ghost/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/iradchenko/sandbox/ember-ghost/node_modules/express/lib/router/index.js:317:13)
    at /Users/iradchenko/sandbox/ember-ghost/node_modules/express/lib/router/index.js:284:7
```

**Comment by mansona** [comment]
@knownasilya are you cloning this so that you can contribute to the underlying engine or are you trying to get your own blog up? just curious 😂 

When I am working on the underlying tech I tend to work with it linked into an app, which probably explains why the dummy app isn't working out of the box 😂

**Comment by knownasilya** [comment]
@mansona any ideas what might be the cause? I'm not too familiar with fastboot.

**Comment by mansona** [comment]
@knownasilya I just hit this issue when trying to install `ember-cli-fastboot` in the ember-ghost addon itself for testing 🤔 

This shouldn't be affecting anyone **using** ember-ghost but only the development of it. Are you following the quick start guide and building an Ember app and installing ember-ghost?

**Comment by knownasilya** [comment]
I was developing a fork of it.

**Comment by mansona** [comment]
ah yes so that's what I was asking! I thought you had built the new app as the instructions indicate, and that's why I was confused because I wasn't able to reproduce it. I **have** been able to reproduce your issue and I know what's going on, even if I don't understand exactly why yet 👍 

I will be looking into this issue soon and reaching out to some of the relevant people for some help

**Comment by ExProbitasFiducia** [comment]
Hi there. I ran into this problem earlier today. It looks like this is an issue cause by the module resolution, when ember-cli-fastboot is installed in the repo. You would need to modify the imports to be relative for the fastboot module and for the fastboot-express-middleware modules, or place these in node_modules so that resolution can work again.

**Comment by mansona** [comment]
@ExProbitasFiducia this isn't an issue that most people should encounter because you should only be cloning this repo and running it if you intend to make a change to the empress-blog core functionality, not if you're trying to build a blog or even trying to write your own template.

A workaround, for now, would be to temporarily delete `ember-cli-fastboot` from devDependencies when trying to run this directly 👍 but again there are very few cases where you might want to run this directly 😂

**Comment by ExProbitasFiducia** [comment]
Agreed. If you are doing something weird though and run into it, it'll be good to have a search result that leaves some to breadcrumbs to follow.

**Comment by mansona** [comment]
@ExProbitasFiducia that's exactly why I wanted to include the temporary fix for it in this message thread 😉

**Comment by mansona** [comment]
@knownasilya @ExProbitasFiducia I just wanted to let you know that I've added a note to the top of the README to remove some confusion around "how to use empress-blog": 

> **Note:** if you have come here wanting to use empress-blog for your own blog then [skip down to the quick-start](#quick-start). You do **not** need to clone this repo to get started, you only need to clone this repo if you want to develop empress-blog 🎉

Please let me know what you think about that and if there is anything that I need to do to improve the message 👍 I want to make this 100% clear that it's super easy to get started with

**Comment by mansona** [comment]
I have fixed the original issue so there is no error any more 👍 and I am satisfied that the note at the top of the Readme solves the fact that there was some confusion
